const ACCOUNT_KEY='nat-admin-account', SESSION_KEY='nat-admin-session';
const POSTS_KEY='nat-admin-posts', DESTS_KEY='nat-admin-destinations', OFFERS_KEY='nat-admin-offers';
let BASEDATA={destinations:[],offers:[],posts:[]}, section='dashboard', editingId=null;
const SB=window.NAT_SUPABASE_CLIENT||null;
let SBUSER=null, SBCACHE={destinations:[],voyages:[],publications:[],requests:[],featured:null};
const ROOT='../';
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const slug=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')||('item-'+Date.now());
const lines=s=>String(s||'').split(/\n|,/).map(x=>x.trim()).filter(Boolean);
const arrText=a=>(a||[]).join('\n');
const imageSrc=p=>/^(https?:|data:|blob:)/i.test(p||'')?p:ROOT+(p||'assets/logo.jpg').replace(/^\.\//,'').replace(/^\//,'');
const STORAGE_BUCKET='site-images';
const MAX_IMAGE_BYTES=8*1024*1024;
function safeFileName(name='image.jpg'){
  const parts=String(name).toLowerCase().split('.');
  const ext=(parts.length>1?parts.pop():'jpg').replace(/[^a-z0-9]/g,'')||'jpg';
  const base=parts.join('.').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')||'image';
  return `${base.slice(0,55)}.${ext}`;
}
function validateImage(file){
  if(!file)return 'Aucun fichier sélectionné.';
  const allowed=['image/jpeg','image/png','image/webp'];
  if(!allowed.includes(file.type))return 'Format accepté : JPG, PNG ou WebP.';
  if(file.size>MAX_IMAGE_BYTES)return 'L’image dépasse 8 Mo.';
  return '';
}
async function sbUploadImageFile(file,folder='media'){
  const bad=validateImage(file);if(bad)throw new Error(bad);
  if(!SB)throw new Error('Service indisponible.');
  const rand=crypto.getRandomValues(new Uint32Array(2)).join('-');
  const path=`${folder}/${Date.now()}-${rand}-${safeFileName(file.name)}`;
  const {error}=await SB.storage.from(STORAGE_BUCKET).upload(path,file,{cacheControl:'3600',upsert:false,contentType:file.type});
  if(error)throw error;
  const {data}=SB.storage.from(STORAGE_BUCKET).getPublicUrl(path);
  if(!data?.publicUrl)throw new Error('URL de l’image introuvable.');
  return data.publicUrl;
}
function imageUploadField(name,label,value,folder){
  const id=`upload-${name}-${Math.random().toString(36).slice(2,8)}`,has=Boolean(value);
  return `<div class="admin-field"><label>${esc(label)}</label><div class="admin-image-uploader ${has?'has-image':'is-empty'}" data-image-field="${esc(name)}"><div class="admin-image-preview"><img data-upload-preview="${esc(name)}" src="${has?imageSrc(value):''}" alt="" ${has?'':'hidden'}><div class="admin-image-empty" data-upload-empty="${esc(name)}" ${has?'hidden':''}>Aucune image</div></div><div class="admin-image-controls"><input type="hidden" name="${esc(name)}" value="${esc(value||'')}"><label class="admin-btn admin-btn-soft admin-upload-btn" for="${id}">Importer une image</label><input id="${id}" class="admin-file-input" type="file" accept="image/jpeg,image/png,image/webp" onchange="sbHandleImagePick(this,'${esc(name)}','${esc(folder)}')"><button type="button" class="admin-btn admin-btn-danger admin-btn-sm" data-remove-image="${esc(name)}" onclick="sbClearImage('${esc(name)}')" ${has?'':'hidden'}>Retirer l’image</button><small>JPG, PNG ou WebP · 8 Mo max.</small></div></div></div>`;
}
function sbSyncImageField(form,name){
  if(!form)return;
  const hidden=form.querySelector(`[name="${name}"]`),preview=form.querySelector(`[data-upload-preview="${name}"]`),empty=form.querySelector(`[data-upload-empty="${name}"]`),remove=form.querySelector(`[data-remove-image="${name}"]`),wrap=form.querySelector(`[data-image-field="${name}"]`),has=Boolean(hidden?.value?.trim());
  if(preview)preview.hidden=!has;
  if(empty)empty.hidden=has;
  if(remove)remove.hidden=!has;
  if(wrap){wrap.classList.toggle('has-image',has);wrap.classList.toggle('is-empty',!has)}
}
async function sbHandleImagePick(input,name,folder){
  const file=input.files?.[0];if(!file)return;
  const form=input.closest('form'),hidden=form?.querySelector(`[name="${name}"]`),preview=form?.querySelector(`[data-upload-preview="${name}"]`),label=input.previousElementSibling;
  const old=label?.textContent;if(label){label.textContent='Import en cours…';label.style.pointerEvents='none'}
  try{
    const url=await sbUploadImageFile(file,folder);
    if(hidden)hidden.value=url;if(preview)preview.src=url;sbSyncImageField(form,name);
    toast('Image importée');
  }catch(err){console.error(err);toast(err?.message||'Impossible d’importer l’image.');input.value=''}
  finally{if(label){label.textContent=old||'Importer une image';label.style.pointerEvents=''}}
}
function sbClearImage(name){const form=$('#sbEdit');if(!form)return;const hidden=form.querySelector(`[name="${name}"]`),input=form.querySelector(`input[type="file"][onchange*="'${name}'"]`);if(hidden)hidden.value='';if(input)input.value='';sbSyncImageField(form,name);toast('Image retirée. Enregistrez pour confirmer.')}
function galleryUploadField(value){
  const id=`upload-gallery-${Math.random().toString(36).slice(2,8)}`;
  return `<div class="admin-field"><label>Galerie</label><textarea name="gallery" class="admin-gallery-values" hidden>${esc(arrText(value||[]))}</textarea><div class="admin-gallery-grid" id="galleryPreview"></div><div class="admin-gallery-actions"><label class="admin-btn admin-btn-soft admin-upload-btn" for="${id}">+ Ajouter des photos</label><input id="${id}" class="admin-file-input" type="file" accept="image/jpeg,image/png,image/webp" multiple onchange="sbHandleGalleryPick(this)"><button type="button" class="admin-btn admin-btn-danger admin-btn-sm" onclick="sbClearGallery()">Vider la galerie</button></div></div>`;
}
function sbGalleryUrls(){const t=$('#sbEdit [name="gallery"]');return lines(t?.value||'')}
function sbRenderGallery(){const box=$('#galleryPreview');if(!box)return;const urls=sbGalleryUrls();box.innerHTML=urls.length?urls.map((u,i)=>`<div class="admin-gallery-item"><img src="${imageSrc(u)}" alt=""><button type="button" aria-label="Retirer cette image" onclick="sbRemoveGalleryImage(${i})">×</button></div>`).join(''):'<div class="admin-gallery-empty">Aucune photo dans la galerie.</div>'}
async function sbHandleGalleryPick(input){const files=[...(input.files||[])];if(!files.length)return;const label=input.previousElementSibling,old=label?.textContent;if(label){label.textContent=`Import de ${files.length} photo${files.length>1?'s':''}…`;label.style.pointerEvents='none'};try{const urls=sbGalleryUrls();for(const file of files){urls.push(await sbUploadImageFile(file,'voyages/galeries'))}const t=$('#sbEdit [name="gallery"]');if(t)t.value=urls.join('\n');sbRenderGallery();toast(files.length>1?'Photos importées':'Photo importée')}catch(err){console.error(err);toast(err?.message||'Impossible d’importer les photos.')}finally{input.value='';if(label){label.textContent=old||'+ Ajouter des photos';label.style.pointerEvents=''}}}
function sbRemoveGalleryImage(i){const urls=sbGalleryUrls();urls.splice(i,1);const t=$('#sbEdit [name="gallery"]');if(t)t.value=urls.join('\n');sbRenderGallery()}
function sbClearGallery(){const t=$('#sbEdit [name="gallery"]');if(t)t.value='';sbRenderGallery()}
function toast(t){const e=$('#toast');if(!e)return;e.textContent=t;e.style.display='block';clearTimeout(window.__at);window.__at=setTimeout(()=>e.style.display='none',2600)}
function b64(buf){return btoa(String.fromCharCode(...new Uint8Array(buf)))} function ub64(s){return Uint8Array.from(atob(s),c=>c.charCodeAt(0))}
async function hashPassword(password,saltB64,iterations=180000){const salt=saltB64?ub64(saltB64):crypto.getRandomValues(new Uint8Array(16));const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(password),'PBKDF2',false,['deriveBits']);const bits=await crypto.subtle.deriveBits({name:'PBKDF2',salt,iterations,hash:'SHA-256'},key,256);return {salt:b64(salt),hash:b64(bits),iterations}}
function account(){try{return JSON.parse(localStorage.getItem(ACCOUNT_KEY)||'null')}catch{return null}} function isLogged(){return sessionStorage.getItem(SESSION_KEY)==='1'}
function getList(key,base){try{const x=JSON.parse(localStorage.getItem(key)||'null');if(Array.isArray(x))return x}catch{}return JSON.parse(JSON.stringify(base||[]))}
const destinations=()=>getList(DESTS_KEY,BASEDATA.destinations), offers=()=>getList(OFFERS_KEY,BASEDATA.offers), posts=()=>getList(POSTS_KEY,BASEDATA.posts);
const save=(key,v)=>localStorage.setItem(key,JSON.stringify(v));
async function init(){try{BASEDATA=await fetch(ROOT+'data.json').then(r=>r.json())}catch{} render()}
function loginLayout(content){$('#adminApp').innerHTML=`<main class="admin-login"><section class="admin-login-visual"><div class="admin-login-brand"><img src="${ROOT}assets/logo.jpg" alt=""><div><strong>New Age Travel France</strong><span>Administration</span></div></div><div class="admin-login-copy"><div class="kicker">Espace professionnel</div><h1>Gérez tout le contenu du site.</h1><p>Destinations, voyages et actualités sont séparés, mais peuvent être liés entre eux pour garder un site clair et cohérent.</p></div></section><section class="admin-login-panel">${content}</section></main>`}
function render(){const a=account();if(!a)return renderSetup();if(!isLogged())return renderLogin(a);renderAdmin(a)}
function renderSetup(){loginLayout(`<div class="admin-auth-card"><div class="kicker">Première utilisation</div><h2>Créer le compte administrateur</h2><p class="muted">Créez les identifiants qui permettront d’accéder à l’espace d’administration.</p><form class="admin-form" id="setupForm"><div class="admin-field"><label>Adresse e-mail administrateur</label><input type="email" name="email" required autocomplete="username" placeholder="admin@agence.fr"></div><div class="admin-field"><label>Mot de passe</label><input type="password" name="password" minlength="10" required autocomplete="new-password" placeholder="10 caractères minimum"></div><div class="admin-field"><label>Confirmer le mot de passe</label><input type="password" name="confirm" minlength="10" required autocomplete="new-password"></div><button class="admin-btn admin-btn-primary">Créer mon accès</button></form></div>`);$('#setupForm').addEventListener('submit',setup)}
async function setup(e){e.preventDefault();const f=new FormData(e.currentTarget),email=f.get('email').trim().toLowerCase(),pw=f.get('password');if(pw!==f.get('confirm'))return toast('Les deux mots de passe sont différents.');if(pw.length<10)return toast('Choisissez au moins 10 caractères.');const h=await hashPassword(pw);localStorage.setItem(ACCOUNT_KEY,JSON.stringify({email,...h,createdAt:new Date().toISOString()}));sessionStorage.setItem(SESSION_KEY,'1');render()}
function renderLogin(a){loginLayout(`<div class="admin-auth-card"><div class="kicker">Connexion</div><h2>Bienvenue.</h2><p class="muted">Connectez-vous pour accéder à l’administration.</p><form class="admin-form" id="loginForm"><div class="admin-field"><label>E-mail</label><input type="email" name="email" required autocomplete="username" value="${esc(a.email)}"></div><div class="admin-field"><label>Mot de passe</label><input type="password" name="password" required autocomplete="current-password"></div><button class="admin-btn admin-btn-primary">Se connecter</button></form><a href="${ROOT}" style="display:block;margin-top:18px;text-align:center;color:#47627f;text-decoration:none">← Retour au site</a></div>`);$('#loginForm').addEventListener('submit',login)}
async function login(e){e.preventDefault();const f=new FormData(e.currentTarget),a=account();if(f.get('email').trim().toLowerCase()!==a.email)return toast('Identifiants incorrects.');const h=await hashPassword(f.get('password'),a.salt,a.iterations);if(h.hash!==a.hash)return toast('Identifiants incorrects.');sessionStorage.setItem(SESSION_KEY,'1');render()}
function logout(){sessionStorage.removeItem(SESSION_KEY);render()}
function navBtn(id,label,ico){return `<button class="${section===id?'active':''}" onclick="go('${id}')"><span>${ico}</span>${label}</button>`}
function titleFor(){return ({dashboard:'Tableau de bord',destinations:'Destinations',voyages:'Voyages',publications:'Publications',security:'Compte & sécurité'})[section]||'Administration'}
function renderAdmin(a){$('#adminApp').innerHTML=`<div class="admin-overlay" id="adminOverlay" onclick="toggleSidebar(false)"></div><div class="admin-shell"><aside class="admin-sidebar" id="adminSidebar"><div class="admin-logo"><img src="${ROOT}assets/logo.jpg" alt=""><div><strong>New Age Travel</strong><small>Administration</small></div></div><nav class="admin-nav">${navBtn('dashboard','Tableau de bord','⌂')}${navBtn('destinations','Destinations','🌍')}${navBtn('voyages','Voyages','✈')}${navBtn('publications','Publications','▤')}${navBtn('security','Compte & sécurité','⚙')}<a href="${ROOT}" target="_blank"><span>↗</span>Voir le site</a></nav><div class="admin-sidebar-bottom"><div class="admin-user">${esc(a.email)}</div><button class="admin-btn admin-logout" onclick="logout()">Se déconnecter</button></div></aside><main class="admin-main"><header class="admin-top"><div style="display:flex;align-items:center;gap:12px"><button class="admin-mobile-menu" onclick="toggleSidebar()">☰</button><h1>${titleFor()}</h1></div><div class="admin-top-actions"><a class="admin-btn admin-btn-soft admin-btn-sm" href="${ROOT}" target="_blank">Voir le site ↗</a></div></header><div class="admin-content" id="adminContent"></div></main></div>`;renderSection()}
function go(s){section=s;editingId=null;renderAdmin(account());toggleSidebar(false)}
function toggleSidebar(force){const sb=$('#adminSidebar'),ov=$('#adminOverlay');if(!sb)return;const open=force===undefined?!sb.classList.contains('open'):force;sb.classList.toggle('open',open);ov.classList.toggle('open',open)}
function renderSection(){if(section==='dashboard')dashboard();else if(section==='destinations')destinationList();else if(section==='voyages')voyageList();else if(section==='publications')publicationList();else security()}
function statusPill(x){return `<span class="status-pill ${x.active!==false?'status-on':'status-off'}">${x.active!==false?'Publié':'Masqué'}</span>`}
function dashboard(){const d=destinations(),o=offers(),p=posts();$('#adminContent').innerHTML=`<div class="admin-head"><div><div class="kicker">Vue d’ensemble</div><h2>Contenu du site</h2><p class="muted">Chaque module a son rôle : destination = inspiration, voyage = offre commerciale, publication = actualité.</p></div><button class="admin-btn admin-btn-primary" onclick="go('voyages');setTimeout(()=>editVoyage(),0)">+ Ajouter un voyage</button></div><div class="admin-kpis admin-kpis-4"><div class="admin-kpi"><span>Destinations</span><strong>${d.length}</strong><small>${d.filter(x=>x.active!==false).length} publiées</small></div><div class="admin-kpi"><span>Voyages</span><strong>${o.length}</strong><small>${o.filter(x=>x.active!==false).length} publiés</small></div><div class="admin-kpi"><span>Publications</span><strong>${p.length}</strong><small>${p.filter(x=>x.active!==false).length} publiées</small></div><div class="admin-kpi"><span>Relations</span><strong>${o.filter(x=>x.destinationId).length}</strong><small>voyages liés à une destination</small></div></div><div class="admin-help-grid"><div class="admin-card"><h3>🌍 Destinations</h3><p class="muted">Pages d’inspiration qui regroupent leurs voyages et actualités liés.</p><button class="admin-btn admin-btn-soft" onclick="go('destinations')">Gérer</button></div><div class="admin-card"><h3>✈️ Voyages</h3><p class="muted">Offres concrètes avec prix, dates, durée, programme et destination associée.</p><button class="admin-btn admin-btn-soft" onclick="go('voyages')">Gérer</button></div><div class="admin-card"><h3>▤ Publications</h3><p class="muted">Actualités pouvant pointer automatiquement vers un voyage ou une destination.</p><button class="admin-btn admin-btn-soft" onclick="go('publications')">Gérer</button></div></div>`}
function genericTable(kind,list,cols,row){if(!list.length)return '<div class="empty-admin">Aucun contenu pour le moment.</div>';return `<div class="admin-table-wrap"><table class="admin-table"><thead><tr>${cols.map(c=>`<th>${c}</th>`).join('')}<th style="text-align:right">Actions</th></tr></thead><tbody>${list.map(x=>row(x)).join('')}</tbody></table></div>`}
function actions(kind,id,isActive){const cap=kind[0].toUpperCase()+kind.slice(1);return `<div class="row-actions"><button class="admin-btn admin-btn-soft admin-btn-sm" onclick="toggleItem('${kind}','${esc(id)}')">${isActive?'Masquer':'Publier'}</button><button class="admin-btn admin-btn-dark admin-btn-sm" onclick="edit${cap}('${esc(id)}')">Modifier</button><button class="admin-btn admin-btn-danger admin-btn-sm" onclick="deleteItem('${kind}','${esc(id)}')">Supprimer</button></div>`}
function destinationList(){const d=destinations();$('#adminContent').innerHTML=`<div class="admin-head"><div><div class="kicker">Inspiration</div><h2>Destinations</h2><p class="muted">Une destination regroupe les voyages et publications qui lui sont associés.</p></div><button class="admin-btn admin-btn-primary" onclick="editDestination()">+ Nouvelle destination</button></div><div class="admin-panel">${genericTable('destination',d,['Destination','Univers','Voyages liés','Statut'],x=>`<tr><td><div class="pub-cell"><img src="${imageSrc(x.image)}" alt=""><div><strong>${esc(x.name)}</strong><small>${esc(x.region||'')}</small></div></div></td><td>${esc(x.category||'—')}</td><td>${offers().filter(o=>o.destinationId===x.id).length}</td><td>${statusPill(x)}</td><td>${actions('destination',x.id,x.active!==false)}</td></tr>`)}</div>`}
function voyageList(){const o=offers(), d=destinations();$('#adminContent').innerHTML=`<div class="admin-head"><div><div class="kicker">Catalogue</div><h2>Voyages</h2><p class="muted">Gérez les offres commerciales et reliez chaque voyage à sa destination.</p></div><button class="admin-btn admin-btn-primary" onclick="editVoyage()">+ Nouveau voyage</button></div><div class="admin-panel">${genericTable('voyage',o,['Voyage','Destination','Prix','Statut'],x=>{const dest=d.find(z=>z.id===x.destinationId);return `<tr><td><div class="pub-cell"><img src="${imageSrc(x.image)}" alt=""><div><strong>${esc(x.title)} ${sbFeaturedBadge('voyage',x.id)}</strong><small>${esc(x.date||'')}</small></div></div></td><td>${esc(dest?.name||'Non liée')}</td><td>${esc(x.price||'—')}</td><td>${statusPill(x)}</td><td>${actions('voyage',x.id,x.active!==false)}</td></tr>`})}</div>`}
function publicationList(){const p=posts(),o=offers(),d=destinations();$('#adminContent').innerHTML=`<div class="admin-head"><div><div class="kicker">Actualités</div><h2>Publications</h2><p class="muted">Reliez une publication à un voyage ou une destination : le bouton public pointera automatiquement vers le bon contenu.</p></div><button class="admin-btn admin-btn-primary" onclick="editPublication()">+ Nouvelle publication</button></div><div class="admin-panel">${genericTable('publication',p,['Publication','Lien associé','Date','Statut'],x=>{const rel=o.find(z=>z.id===x.offerId)?.title||d.find(z=>z.id===x.destinationId)?.name||'Contact';return `<tr><td><div class="pub-cell"><img src="${imageSrc(x.image)}" alt=""><div><strong>${esc(x.title)}</strong><small>${esc((x.text||'').slice(0,58))}</small></div></div></td><td>${esc(rel)}</td><td>${esc(x.date||'—')}</td><td>${statusPill(x)}</td><td>${actions('publication',x.id,x.active!==false)}</td></tr>`})}</div>`}
function previewCard(title,image,text,meta='Aperçu'){return `<aside class="admin-card"><h3>Aperçu</h3><div class="preview-post"><img id="previewImage" src="${imageSrc(image)}" alt=""><div class="preview-post-body"><div class="kicker" id="previewMeta">${esc(meta)}</div><h3 id="previewTitle">${esc(title||'Titre')}</h3><p id="previewText">${esc(text||'Votre texte apparaîtra ici.')}</p></div></div></aside>`}
function editDestination(id){editingId=id||null;const x=id?destinations().find(z=>z.id===id):{id:'',name:'',region:'',category:'afrique',image:'assets/cairo.jpg',description:'',price:'Sur demande',priceValue:null,duration:'Selon programme',departure:'Marseille',highlights:[],badge:'',active:true};section='destinations';editorShell('Destination',id,`<form id="editForm" class="admin-editor"><div class="admin-card"><h3>Informations</h3><div class="admin-form"><div class="admin-fields-2"><div class="admin-field"><label>Nom *</label><input name="name" required value="${esc(x.name)}"></div><div class="admin-field"><label>Région / pays *</label><input name="region" required value="${esc(x.region)}"></div></div><div class="admin-fields-2"><div class="admin-field"><label>Univers</label><select name="category"><option value="afrique" ${x.category==='afrique'?'selected':''}>Afrique</option><option value="spirituel" ${x.category==='spirituel'?'selected':''}>Spirituel</option><option value="mediterranee" ${x.category==='mediterranee'?'selected':''}>Méditerranée</option></select></div><div class="admin-field"><label>Badge</label><input name="badge" value="${esc(x.badge||'')}"></div></div><div class="admin-field"><label>Description *</label><textarea name="description" required>${esc(x.description)}</textarea></div><div class="admin-fields-2"><div class="admin-field"><label>Prix affiché</label><input name="price" value="${esc(x.price||'')}"></div><div class="admin-field"><label>Prix numérique (€)</label><input name="priceValue" type="number" min="0" value="${esc(x.priceValue??'')}"></div></div><div class="admin-fields-2"><div class="admin-field"><label>Durée</label><input name="duration" value="${esc(x.duration||'')}"></div><div class="admin-field"><label>Départ</label><input name="departure" value="${esc(x.departure||'Marseille')}"></div></div><div class="admin-field"><label>Image</label><input name="image" value="${esc(x.image||'')}"></div><div class="admin-field"><label>Temps forts (1 par ligne)</label><textarea name="highlights">${esc(arrText(x.highlights))}</textarea></div>${switchField(x.active!==false,'Destination visible')}<div class="editor-actions"><button class="admin-btn admin-btn-primary">Enregistrer</button><button type="button" class="admin-btn admin-btn-soft" onclick="destinationList()">Annuler</button></div><input type="hidden" name="id" value="${esc(x.id)}"></div></div>${previewCard(x.name,x.image,x.description,x.region)}</form>`);bindEditor('destination')}
function editVoyage(id){editingId=id||null;const x=id?offers().find(z=>z.id===id):{id:'',destinationId:'',title:'',subtitle:'',date:'',image:'assets/cairo.jpg',price:'Sur demande',priceValue:null,duration:'',departure:'Marseille',text:'',included:[],highlights:[],gallery:[],badge:'',active:true};section='voyages';const opts=destinations().map(d=>`<option value="${esc(d.id)}" ${x.destinationId===d.id?'selected':''}>${esc(d.name)}</option>`).join('');editorShell('Voyage',id,`<form id="editForm" class="admin-editor"><div class="admin-card"><h3>Informations</h3><div class="admin-form"><div class="admin-field"><label>Destination associée *</label><select name="destinationId" required><option value="">Choisir…</option>${opts}</select></div><div class="admin-fields-2"><div class="admin-field"><label>Titre *</label><input name="title" required value="${esc(x.title)}"></div><div class="admin-field"><label>Date / période</label><input name="date" value="${esc(x.date||'')}"></div></div><div class="admin-field"><label>Sous-titre</label><input name="subtitle" value="${esc(x.subtitle||'')}"></div><div class="admin-field"><label>Présentation *</label><textarea name="text" required>${esc(x.text)}</textarea></div><div class="admin-fields-2"><div class="admin-field"><label>Prix affiché</label><input name="price" value="${esc(x.price||'')}"></div><div class="admin-field"><label>Prix numérique (€)</label><input name="priceValue" type="number" min="0" value="${esc(x.priceValue??'')}"></div></div><div class="admin-fields-2"><div class="admin-field"><label>Durée</label><input name="duration" value="${esc(x.duration||'')}"></div><div class="admin-field"><label>Départ</label><input name="departure" value="${esc(x.departure||'Marseille')}"></div></div><div class="admin-fields-2"><div class="admin-field"><label>Badge</label><input name="badge" value="${esc(x.badge||'')}"></div><div class="admin-field"><label>Image principale</label><input name="image" value="${esc(x.image||'')}"></div></div><div class="admin-field"><label>Inclus (1 par ligne)</label><textarea name="included">${esc(arrText(x.included))}</textarea></div><div class="admin-field"><label>Temps forts (1 par ligne)</label><textarea name="highlights">${esc(arrText(x.highlights))}</textarea></div><div class="admin-field"><label>Galerie — chemins d’images (1 par ligne)</label><textarea name="gallery">${esc(arrText(x.gallery))}</textarea></div>${switchField(x.active!==false,'Voyage visible')}<div class="editor-actions"><button class="admin-btn admin-btn-primary">Enregistrer</button><button type="button" class="admin-btn admin-btn-soft" onclick="voyageList()">Annuler</button></div><input type="hidden" name="id" value="${esc(x.id)}"></div></div>${previewCard(x.title,x.image,x.text,x.date)}</form>`);bindEditor('voyage')}
function editPublication(id){editingId=id||null;const x=id?posts().find(z=>z.id===id):{id:'',title:'',date:new Intl.DateTimeFormat('fr-FR',{day:'numeric',month:'short'}).format(new Date()),text:'',image:'assets/cairo.jpg',offerId:'',destinationId:'',active:true};section='publications';const offerOpts=offers().map(o=>`<option value="${esc(o.id)}" ${x.offerId===o.id?'selected':''}>${esc(o.title)}</option>`).join(''), destOpts=destinations().map(d=>`<option value="${esc(d.id)}" ${x.destinationId===d.id?'selected':''}>${esc(d.name)}</option>`).join('');editorShell('Publication',id,`<form id="editForm" class="admin-editor"><div class="admin-card"><h3>Contenu & relation</h3><div class="admin-form"><div class="admin-fields-2"><div class="admin-field"><label>Titre *</label><input name="title" required value="${esc(x.title)}"></div><div class="admin-field"><label>Date affichée</label><input name="date" value="${esc(x.date||'')}"></div></div><div class="admin-field"><label>Texte *</label><textarea name="text" required>${esc(x.text)}</textarea></div><div class="admin-field"><label>Image</label><input name="image" value="${esc(x.image||'')}"></div><div class="admin-fields-2"><div class="admin-field"><label>Voyage associé</label><select name="offerId"><option value="">Aucun</option>${offerOpts}</select></div><div class="admin-field"><label>Destination associée</label><select name="destinationId"><option value="">Aucune</option>${destOpts}</select></div></div><div class="admin-note">Si un voyage est choisi, le bouton de la publication ouvrira automatiquement ce voyage. Sinon, il ouvrira la destination associée. Sans relation, il renverra vers Contact.</div>${switchField(x.active!==false,'Publication visible')}<div class="editor-actions"><button class="admin-btn admin-btn-primary">Enregistrer</button><button type="button" class="admin-btn admin-btn-soft" onclick="publicationList()">Annuler</button></div><input type="hidden" name="id" value="${esc(x.id)}"></div></div>${previewCard(x.title,x.image,x.text,x.date)}</form>`);bindEditor('publication')}
function editorShell(label,id,body){$('#adminContent').innerHTML=`<div class="admin-head"><div><div class="kicker">${id?'Modification':'Création'}</div><h2>${id?'Modifier':'Ajouter'} ${label.toLowerCase()}</h2><p class="muted">Les changements sont visibles sur ce navigateur dès l’enregistrement.</p></div></div>${body}`}
function switchField(on,label){return `<div class="admin-switch-row"><div><strong>${label}</strong><div class="muted" style="font-size:13px">Désactivez pour conserver le contenu sans l’afficher publiquement.</div></div><label class="admin-switch"><input type="checkbox" name="active" ${on?'checked':''}><span></span></label></div>`}
function bindEditor(kind){const f=$('#editForm');f.addEventListener('input',()=>{const fd=new FormData(f);$('#previewTitle').textContent=fd.get(kind==='destination'?'name':'title')||'Titre';$('#previewText').textContent=fd.get(kind==='destination'?'description':'text')||'Votre texte apparaîtra ici.';$('#previewMeta').textContent=fd.get(kind==='destination'?'region':'date')||'Aperçu';$('#previewImage').src=imageSrc(fd.get('image')||'assets/logo.jpg')});f.addEventListener('submit',e=>saveEditor(e,kind))}
function saveEditor(e,kind){e.preventDefault();const f=new FormData(e.currentTarget);if(kind==='destination'){let list=destinations();const oldId=f.get('id'), id=oldId||slug(f.get('name'));const item={id,name:f.get('name').trim(),region:f.get('region').trim(),category:f.get('category'),image:f.get('image').trim()||'assets/logo.jpg',description:f.get('description').trim(),price:f.get('price').trim()||'Sur demande',priceValue:f.get('priceValue')?Number(f.get('priceValue')):null,duration:f.get('duration').trim(),departure:f.get('departure').trim()||'Marseille',highlights:lines(f.get('highlights')),badge:f.get('badge').trim(),active:f.get('active')==='on'};upsert(list,item);save(DESTS_KEY,list);toast('Destination enregistrée');destinationList()}else if(kind==='voyage'){let list=offers();const oldId=f.get('id'), id=oldId||slug(f.get('title'))+'-'+Date.now().toString().slice(-4);const item={id,destinationId:f.get('destinationId'),title:f.get('title').trim(),subtitle:f.get('subtitle').trim(),date:f.get('date').trim(),image:f.get('image').trim()||'assets/logo.jpg',price:f.get('price').trim()||'Sur demande',priceValue:f.get('priceValue')?Number(f.get('priceValue')):null,duration:f.get('duration').trim(),departure:f.get('departure').trim()||'Marseille',text:f.get('text').trim(),included:lines(f.get('included')),highlights:lines(f.get('highlights')),gallery:lines(f.get('gallery')),badge:f.get('badge').trim(),active:f.get('active')==='on'};upsert(list,item);save(OFFERS_KEY,list);syncDestinationOffer(item);toast('Voyage enregistré');voyageList()}else{let list=posts();const oldId=f.get('id'), id=oldId||slug(f.get('title'))+'-'+Date.now().toString().slice(-4), offerId=f.get('offerId'), offer=offers().find(o=>o.id===offerId);const item={id,title:f.get('title').trim(),date:f.get('date').trim(),text:f.get('text').trim(),image:f.get('image').trim()||'assets/logo.jpg',offerId:offerId||'',destinationId:offer?.destinationId||f.get('destinationId')||'',active:f.get('active')==='on'};upsert(list,item);save(POSTS_KEY,list);toast('Publication enregistrée');publicationList()}}
function upsert(list,item){const i=list.findIndex(x=>x.id===item.id);if(i>=0)list[i]=item;else list.unshift(item)}
function syncDestinationOffer(o){let d=destinations(), target=d.find(x=>x.id===o.destinationId);if(target&&!target.offerId){target.offerId=o.id;save(DESTS_KEY,d)}}
function toggleItem(kind,id){const map={destination:[DESTS_KEY,destinations,destinationList],voyage:[OFFERS_KEY,offers,voyageList],publication:[POSTS_KEY,posts,publicationList]},[key,get,renderList]=map[kind],list=get(),x=list.find(z=>z.id===id);if(!x)return;x.active=x.active===false;save(key,list);toast(x.active?'Contenu publié':'Contenu masqué');renderList()}
function deleteItem(kind,id){if(kind==='destination'){const linked=offers().filter(o=>o.destinationId===id);if(linked.length)return toast(`Impossible : ${linked.length} voyage(s) sont liés à cette destination.`);if(!confirm('Supprimer cette destination ?'))return;save(DESTS_KEY,destinations().filter(x=>x.id!==id));const p=posts().map(x=>x.destinationId===id?{...x,destinationId:''}:x);save(POSTS_KEY,p);destinationList()}else if(kind==='voyage'){if(!confirm('Supprimer ce voyage ? Les publications liées seront conservées mais détachées.'))return;save(OFFERS_KEY,offers().filter(x=>x.id!==id));save(POSTS_KEY,posts().map(x=>x.offerId===id?{...x,offerId:''}:x));let d=destinations().map(x=>x.offerId===id?{...x,offerId:''}:x);save(DESTS_KEY,d);voyageList()}else{if(!confirm('Supprimer cette publication ?'))return;save(POSTS_KEY,posts().filter(x=>x.id!==id));publicationList()}toast('Suppression effectuée')}
function security(){const a=account();$('#adminContent').innerHTML=`<div class="admin-head"><div><div class="kicker">Compte administrateur</div><h2>Compte & sécurité</h2><p class="muted">Gérez les informations et la sécurité de votre compte administrateur.</p></div><span class="security-badge">Session active</span></div><div class="security-grid"><form class="admin-card admin-form" id="passwordForm"><h3>Changer le mot de passe</h3><div class="admin-field"><label>Mot de passe actuel</label><input name="current" type="password" required autocomplete="current-password"></div><div class="admin-field"><label>Nouveau mot de passe</label><input name="next" type="password" minlength="10" required autocomplete="new-password"></div><div class="admin-field"><label>Confirmer le nouveau mot de passe</label><input name="confirm" type="password" minlength="10" required autocomplete="new-password"></div><button class="admin-btn admin-btn-primary">Mettre à jour le mot de passe</button></form><div class="admin-card"><h3>Informations du compte</h3><p class="muted">Compte administrateur</p><p><strong>${esc(a.email)}</strong></p><hr style="border:0;border-top:1px solid #edf1f5;margin:22px 0"><p class="muted" style="font-size:13px;line-height:1.6">Utilisez un mot de passe unique et difficile à deviner.</p></div></div>`;$('#passwordForm').addEventListener('submit',changePassword)}
async function changePassword(e){e.preventDefault();const f=new FormData(e.currentTarget),a=account(),cur=await hashPassword(f.get('current'),a.salt,a.iterations);if(cur.hash!==a.hash)return toast('Le mot de passe actuel est incorrect.');if(f.get('next')!==f.get('confirm'))return toast('Les nouveaux mots de passe sont différents.');if(String(f.get('next')).length<10)return toast('Choisissez au moins 10 caractères.');const h=await hashPassword(f.get('next'));localStorage.setItem(ACCOUNT_KEY,JSON.stringify({...a,...h,updatedAt:new Date().toISOString()}));e.currentTarget.reset();toast('Mot de passe mis à jour')}
function resetPreview(){if(!confirm('Réinitialiser le compte local et toutes les modifications sur cet appareil ?'))return;[ACCOUNT_KEY,DESTS_KEY,OFFERS_KEY,POSTS_KEY].forEach(k=>localStorage.removeItem(k));sessionStorage.removeItem(SESSION_KEY);render()}
// Aliases utilisés par les boutons générés.
const editdestination=editDestination, editvoyage=editVoyage, editpublication=editPublication;
if(SB) initSupabaseAdmin(); else init();


// =========================
// MODE SUPABASE SÉCURISÉ
// =========================
async function initSupabaseAdmin(){
  const {data:{session}}=await SB.auth.getSession();
  if(!session) return sbRenderLogin();
  const ok=await sbLoadUser(session.user);
  if(!ok){await SB.auth.signOut();return sbRenderDenied()}
  await sbRefresh();
  sbRenderAdmin();
  SB.auth.onAuthStateChange(async(event,session)=>{if(event==='SIGNED_OUT'||!session){SBUSER=null;sbRenderLogin()}});
}
async function sbLoadUser(user){
  const {data,error}=await SB.from('profiles').select('user_id,email,role').eq('user_id',user.id).maybeSingle();
  if(error){console.error(error);return false}
  if(!data||data.role!=='admin')return false;
  SBUSER={...user,profile:data};return true;
}
function sbLoginLayout(content,caption='Espace d’administration'){
  $('#adminApp').innerHTML=`<main class="admin-login"><section class="admin-login-visual"><div class="admin-login-brand"><img src="${ROOT}assets/logo.jpg" alt=""><div><strong>New Age Travel France</strong><span>Administration</span></div></div><div class="admin-login-copy"><div class="kicker">Espace professionnel</div><h1>Gérez le site depuis un seul endroit.</h1><p>Destinations, voyages, publications et demandes clients sont centralisés dans une base sécurisée.</p></div><small style="position:relative;z-index:1;color:#9eb7d1">${caption}</small></section><section class="admin-login-panel">${content}</section></main>`
}
function sbRenderLogin(){
  sbLoginLayout(`<div class="admin-auth-card"><div class="kicker">Administration</div><h2>Connexion</h2><p class="muted">Saisissez vos identifiants pour accéder à l’administration.</p><form class="admin-form" id="sbLoginForm"><div class="admin-field"><label>Adresse e-mail</label><input type="email" name="email" required autocomplete="username" placeholder="admin@agence.fr"></div><div class="admin-field"><label>Mot de passe</label><input type="password" name="password" required autocomplete="current-password"></div><button class="admin-btn admin-btn-primary">Se connecter</button></form><a href="${ROOT}" style="display:block;margin-top:18px;text-align:center;color:#47627f;text-decoration:none">← Retour au site</a></div>`);
  $('#sbLoginForm').addEventListener('submit',sbLogin)
}
async function sbLogin(e){
  e.preventDefault();const f=new FormData(e.currentTarget),btn=e.currentTarget.querySelector('button');btn.disabled=true;btn.textContent='Connexion…';
  const {data,error}=await SB.auth.signInWithPassword({email:String(f.get('email')).trim(),password:String(f.get('password'))});
  if(error){btn.disabled=false;btn.textContent='Se connecter';return toast('E-mail ou mot de passe incorrect.')}
  const ok=await sbLoadUser(data.user);
  if(!ok){await SB.auth.signOut();return sbRenderDenied()}
  await sbRefresh();sbRenderAdmin()
}
function sbRenderDenied(){
  sbLoginLayout(`<div class="admin-auth-card"><div class="kicker">Accès refusé</div><h2>Compte non autorisé</h2><p class="muted">Ce compte ne dispose pas des autorisations nécessaires pour accéder à l’administration.</p><button class="admin-btn admin-btn-primary" onclick="sbRenderLogin()">Retour à la connexion</button></div>`,'Accès réservé aux administrateurs')
}
async function sbLogout(){await SB.auth.signOut();SBUSER=null;sbRenderLogin()}
async function sbRefresh(){
  const [d,v,p,q,s]=await Promise.all([
    SB.from('destinations').select('*').order('created_at',{ascending:true}),
    SB.from('voyages').select('*').order('created_at',{ascending:true}),
    SB.from('publications').select('*').order('created_at',{ascending:false}),
    SB.from('quote_requests').select('*').order('created_at',{ascending:false}),
    SB.from('site_settings').select('*').eq('key','homepage').maybeSingle()
  ]);
  const err=d.error||v.error||p.error||q.error||s.error;if(err){console.error(err);toast('Impossible de charger les données pour le moment')}
  SBCACHE={destinations:d.data||[],voyages:v.data||[],publications:p.data||[],requests:q.data||[],featured:s.data||null}
}
function sbNavBtn(id,label,ico){return `<button class="${section===id?'active':''}" onclick="sbGo('${id}')"><span>${ico}</span>${label}</button>`}
function sbTitle(){return ({dashboard:'Tableau de bord',destinations:'Destinations',voyages:'Voyages',publications:'Publications',requests:'Demandes clients',security:'Compte & sécurité'})[section]||'Administration'}
function sbRenderAdmin(){
  const email=SBUSER?.email||SBUSER?.profile?.email||'';
  $('#adminApp').innerHTML=`<div class="admin-overlay" id="adminOverlay" onclick="toggleSidebar(false)"></div><div class="admin-shell"><aside class="admin-sidebar" id="adminSidebar"><div class="admin-logo"><img src="${ROOT}assets/logo.jpg" alt=""><div><strong>New Age Travel</strong><small>Administration</small></div></div><nav class="admin-nav">${sbNavBtn('dashboard','Tableau de bord','⌂')}${sbNavBtn('destinations','Destinations','🌍')}${sbNavBtn('voyages','Voyages','✈')}${sbNavBtn('publications','Publications','▤')}${sbNavBtn('requests','Demandes clients','✉')}${sbNavBtn('security','Compte & sécurité','⚙')}<a href="${ROOT}" target="_blank"><span>↗</span>Voir le site</a></nav><div class="admin-sidebar-bottom"><div class="admin-user">${esc(email)}</div><button class="admin-btn admin-logout" onclick="sbLogout()">Se déconnecter</button></div></aside><main class="admin-main"><header class="admin-top"><div style="display:flex;align-items:center;gap:12px"><button class="admin-mobile-menu" onclick="toggleSidebar()">☰</button><h1>${sbTitle()}</h1></div><div class="admin-top-actions"><span class="security-badge">Session active</span></div></header><div class="admin-content" id="adminContent"></div></main></div>`;
  sbRenderSection()
}
function sbGo(s){section=s;editingId=null;sbRenderAdmin();toggleSidebar(false)}
function sbRenderSection(){if(section==='dashboard')sbDashboard();else if(section==='destinations')sbListDestinations();else if(section==='voyages')sbListVoyages();else if(section==='publications')sbListPublications();else if(section==='requests')sbListRequests();else sbSecurity()}
function sbStatus(active){return `<span class="status-pill ${active?'status-on':'status-off'}">${active?'Publié':'Masqué'}</span>`}
function sbIsFeatured(type,id){return SBCACHE.featured?.featured_type===type&&SBCACHE.featured?.featured_id===id}
function sbFeaturedBadge(type,id){return sbIsFeatured(type,id)?'<span class="status-pill featured-pill">À la une</span>':''}
function sbFeaturedSwitch(type,id){return `<div class="admin-switch-row featured-switch-row"><div><strong>À la une sur l’accueil</strong></div><label class="admin-switch"><input type="checkbox" name="featured" ${id&&sbIsFeatured(type,id)?'checked':''}><span></span></label></div>`}
async function sbSaveFeatured(type,id,on){
  if(on){
    const {error}=await SB.from('site_settings').upsert({key:'homepage',featured_type:type,featured_id:id,updated_at:new Date().toISOString()});
    if(error)throw error;
  }else if(sbIsFeatured(type,id)){
    const {error}=await SB.from('site_settings').upsert({key:'homepage',featured_type:null,featured_id:null,updated_at:new Date().toISOString()});
    if(error)throw error;
  }
}
function sbDashboard(){
  const d=SBCACHE.destinations,v=SBCACHE.voyages,p=SBCACHE.publications,q=SBCACHE.requests,newq=q.filter(x=>x.status==='nouvelle');
  $('#adminContent').innerHTML=`<div class="admin-head"><div><div class="kicker">Vue d’ensemble</div><h2>Contenu du site</h2><p class="muted">Gérez les destinations, voyages, publications et demandes clients depuis un seul espace.</p></div><button class="admin-btn admin-btn-primary" onclick="sbEditVoyage()">+ Ajouter un voyage</button></div><div class="admin-kpis admin-kpis-4"><div class="admin-kpi"><span>Destinations</span><strong>${d.length}</strong><small>${d.filter(x=>x.active).length} publiées</small></div><div class="admin-kpi"><span>Voyages</span><strong>${v.length}</strong><small>${v.filter(x=>x.active).length} publiés</small></div><div class="admin-kpi"><span>Publications</span><strong>${p.length}</strong><small>${p.filter(x=>x.active).length} publiées</small></div><div class="admin-kpi"><span>Nouvelles demandes</span><strong>${newq.length}</strong><small>${q.length} au total</small></div></div><div class="admin-help-grid"><div class="admin-card"><h3>✈️ Voyages</h3><p class="muted">Gérez les offres, prix, dates, programmes et leur destination.</p><button class="admin-btn admin-btn-soft" onclick="sbGo('voyages')">Gérer</button></div><div class="admin-card"><h3>▤ Publications</h3><p class="muted">Publiez les actualités et reliez-les à un voyage ou une destination.</p><button class="admin-btn admin-btn-soft" onclick="sbGo('publications')">Gérer</button></div><div class="admin-card"><h3>✉ Demandes</h3><p class="muted">Les formulaires envoyés par les clients arrivent ici sans être publics.</p><button class="admin-btn admin-btn-soft" onclick="sbGo('requests')">Consulter</button></div></div>`
}
function sbImage(p){return imageSrc(p||'assets/logo.jpg')}
function sbPanel(title,button,rows,empty='Aucun contenu.'){$('#adminContent').innerHTML=`<div class="admin-head"><div><div class="kicker">Gestion</div><h2>${title}</h2></div>${button||''}</div><div class="admin-panel"><div class="admin-table-wrap"><table class="admin-table"><thead>${rows.head}</thead><tbody>${rows.body||`<tr><td colspan="6" class="empty-admin">${empty}</td></tr>`}</tbody></table></div></div>`}
function sbListDestinations(){const body=SBCACHE.destinations.map(x=>`<tr><td><div class="pub-cell"><img src="${sbImage(x.image)}"><div><strong>${esc(x.name)}</strong><small>${esc(x.region||'')}</small></div></div></td><td>${esc(x.category||'')}</td><td>${esc(x.price||'')}</td><td>${sbStatus(x.active)}</td><td><div class="row-actions"><button class="admin-btn admin-btn-soft admin-btn-sm" onclick="sbToggle('destinations','${esc(x.id)}',${!x.active})">${x.active?'Masquer':'Publier'}</button><button class="admin-btn admin-btn-dark admin-btn-sm" onclick="sbEditDestination('${esc(x.id)}')">Modifier</button><button class="admin-btn admin-btn-danger admin-btn-sm" onclick="sbDelete('destinations','${esc(x.id)}')">Supprimer</button></div></td></tr>`).join('');sbPanel('Destinations',`<button class="admin-btn admin-btn-primary" onclick="sbEditDestination()">+ Ajouter une destination</button>`,{head:'<tr><th>Destination</th><th>Catégorie</th><th>Prix indicatif</th><th>Statut</th><th></th></tr>',body})}
function sbListVoyages(){const dm=Object.fromEntries(SBCACHE.destinations.map(x=>[x.id,x.name]));const body=SBCACHE.voyages.map(x=>`<tr><td><div class="pub-cell"><img src="${sbImage(x.image)}"><div><strong>${esc(x.title)} ${sbFeaturedBadge('voyage',x.id)}</strong><small>${esc(x.date||'')}</small></div></div></td><td>${esc(dm[x.destination_id]||'Non liée')}</td><td>${esc(x.price||'')}</td><td>${sbStatus(x.active)}</td><td><div class="row-actions"><button class="admin-btn admin-btn-soft admin-btn-sm" onclick="sbToggle('voyages','${esc(x.id)}',${!x.active})">${x.active?'Masquer':'Publier'}</button><button class="admin-btn admin-btn-dark admin-btn-sm" onclick="sbEditVoyage('${esc(x.id)}')">Modifier</button><button class="admin-btn admin-btn-danger admin-btn-sm" onclick="sbDelete('voyages','${esc(x.id)}')">Supprimer</button></div></td></tr>`).join('');sbPanel('Voyages',`<button class="admin-btn admin-btn-primary" onclick="sbEditVoyage()">+ Ajouter un voyage</button>`,{head:'<tr><th>Voyage</th><th>Destination</th><th>Prix</th><th>Statut</th><th></th></tr>',body})}
function sbListPublications(){const body=SBCACHE.publications.map(x=>`<tr><td><div class="pub-cell"><img src="${sbImage(x.image)}"><div><strong>${esc(x.title)} ${sbFeaturedBadge('publication',x.id)}</strong><small>${esc(x.date||'')}</small></div></div></td><td>${esc(x.voyage_id||x.destination_id||'Aucune relation')}</td><td>${sbStatus(x.active)}</td><td><div class="row-actions"><button class="admin-btn admin-btn-soft admin-btn-sm" onclick="sbToggle('publications','${esc(x.id)}',${!x.active})">${x.active?'Masquer':'Publier'}</button><button class="admin-btn admin-btn-dark admin-btn-sm" onclick="sbEditPublication('${esc(x.id)}')">Modifier</button><button class="admin-btn admin-btn-danger admin-btn-sm" onclick="sbDelete('publications','${esc(x.id)}')">Supprimer</button></div></td></tr>`).join('');sbPanel('Publications',`<button class="admin-btn admin-btn-primary" onclick="sbEditPublication()">+ Nouvelle publication</button>`,{head:'<tr><th>Publication</th><th>Relation</th><th>Statut</th><th></th></tr>',body})}
function sbListRequests(){const body=SBCACHE.requests.map(x=>`<tr><td><strong>${esc(x.name)}</strong><br><small>${esc(x.email)} · ${esc(x.phone)}</small></td><td>${esc(x.destination||'À définir')}<br><small>${esc(x.period||'')}</small></td><td>${esc(x.travelers||'')}<br><small>${esc(x.budget||'')}</small></td><td><select onchange="sbRequestStatus('${x.id}',this.value)"><option value="nouvelle" ${x.status==='nouvelle'?'selected':''}>Nouvelle</option><option value="en_cours" ${x.status==='en_cours'?'selected':''}>En cours</option><option value="traitee" ${x.status==='traitee'?'selected':''}>Traitée</option><option value="archivee" ${x.status==='archivee'?'selected':''}>Archivée</option></select></td><td>${new Date(x.created_at).toLocaleString('fr-FR')}</td><td><button class="admin-btn admin-btn-soft admin-btn-sm" onclick="sbShowRequest('${x.id}')">Voir</button></td></tr>`).join('');sbPanel('Demandes clients','',{head:'<tr><th>Client</th><th>Projet</th><th>Voyageurs / budget</th><th>Statut</th><th>Reçue</th><th></th></tr>',body},'Aucune demande reçue pour le moment.')}
function sbShowRequest(id){const x=SBCACHE.requests.find(r=>r.id===id);if(!x)return;$('#adminContent').innerHTML=`<div class="admin-head"><div><div class="kicker">Demande client</div><h2>${esc(x.name)}</h2><p class="muted">Reçue le ${new Date(x.created_at).toLocaleString('fr-FR')}</p></div><button class="admin-btn admin-btn-soft" onclick="sbListRequests()">← Retour</button></div><div class="security-grid"><div class="admin-card"><h3>Coordonnées</h3><p><strong>E-mail</strong><br><a href="mailto:${esc(x.email)}">${esc(x.email)}</a></p><p><strong>Téléphone</strong><br><a href="tel:${esc(x.phone)}">${esc(x.phone)}</a></p></div><div class="admin-card"><h3>Projet</h3><p><strong>Destination</strong><br>${esc(x.destination||'À définir')}</p><p><strong>Période</strong><br>${esc(x.period||'À définir')}</p><p><strong>Voyageurs</strong><br>${esc(x.travelers||'')}</p><p><strong>Budget</strong><br>${esc(x.budget||'À définir')}</p></div><div class="admin-card" style="grid-column:1/-1"><h3>Message</h3><p style="white-space:pre-wrap">${esc(x.message||'Aucun message.')}</p></div></div>`}
async function sbRequestStatus(id,status){const {error}=await SB.from('quote_requests').update({status}).eq('id',id);if(error)return toast('Impossible de modifier le statut.');await sbRefresh();toast('Statut mis à jour')}
function sbSwitch(on,label){return `<div class="admin-switch-row"><div><strong>${label}</strong><div class="muted" style="font-size:13px">Désactivez pour conserver ce contenu sans l’afficher.</div></div><label class="admin-switch"><input type="checkbox" name="active" ${on?'checked':''}><span></span></label></div>`}
function sbEditorHeader(label,id){return `<div class="admin-head"><div><div class="kicker">${id?'Modification':'Création'}</div><h2>${id?'Modifier':'Ajouter'} ${label.toLowerCase()}</h2><p class="muted">Modifiez les informations puis enregistrez vos changements.</p></div><button class="admin-btn admin-btn-soft" onclick="sbGo('${label==='Destination'?'destinations':label==='Voyage'?'voyages':'publications'}')">← Retour</button></div>`}
function sbEditDestination(id){const x=id?SBCACHE.destinations.find(z=>z.id===id):{id:'',name:'',region:'',category:'afrique',image:'assets/logo.jpg',description:'',price:'Sur demande',price_value:null,duration:'',departure:'Marseille',highlights:[],offer_id:'',month:'',travel_type:'Séjour',badge:'',active:true};section='destinations';$('#adminContent').innerHTML=sbEditorHeader('Destination',id)+`<form class="admin-card admin-form" id="sbEdit"><div class="admin-fields-2"><div class="admin-field"><label>Nom *</label><input name="name" required value="${esc(x.name)}"></div><div class="admin-field"><label>Région / pays</label><input name="region" value="${esc(x.region||'')}"></div></div><div class="admin-fields-2"><div class="admin-field"><label>Catégorie</label><select name="category"><option value="afrique" ${x.category==='afrique'?'selected':''}>Afrique</option><option value="spirituel" ${x.category==='spirituel'?'selected':''}>Spirituel</option><option value="mediterranee" ${x.category==='mediterranee'?'selected':''}>Méditerranée</option></select></div><div class="admin-field"><label>Badge</label><input name="badge" value="${esc(x.badge||'')}"></div></div><div class="admin-field"><label>Description *</label><textarea name="description" required>${esc(x.description||'')}</textarea></div><div class="admin-fields-2"><div class="admin-field"><label>Prix affiché</label><input name="price" value="${esc(x.price||'')}"></div><div class="admin-field"><label>Prix numérique</label><input name="price_value" type="number" value="${esc(x.price_value??'')}"></div></div><div class="admin-fields-2"><div class="admin-field"><label>Durée</label><input name="duration" value="${esc(x.duration||'')}"></div><div class="admin-field"><label>Départ</label><input name="departure" value="${esc(x.departure||'Marseille')}"></div></div>${imageUploadField('image','Image principale',x.image,'destinations')}<div class="admin-field"><label>Temps forts — un par ligne</label><textarea name="highlights">${esc(arrText(x.highlights))}</textarea></div>${sbSwitch(x.active,'Destination visible')}<input type="hidden" name="id" value="${esc(x.id)}"><button class="admin-btn admin-btn-primary">Enregistrer</button></form>`;$('#sbEdit').addEventListener('submit',e=>sbSaveDestination(e))}
async function sbSaveDestination(e){e.preventDefault();const f=new FormData(e.currentTarget),id=f.get('id')||slug(f.get('name')),payload={id,name:String(f.get('name')).trim(),region:String(f.get('region')||'').trim(),category:String(f.get('category')||''),image:String(f.get('image')||'').trim(),description:String(f.get('description')||'').trim(),price:String(f.get('price')||'Sur demande').trim(),price_value:f.get('price_value')?Number(f.get('price_value')):null,duration:String(f.get('duration')||'').trim(),departure:String(f.get('departure')||'Marseille').trim(),highlights:lines(f.get('highlights')),badge:String(f.get('badge')||'').trim(),active:f.get('active')==='on'};const {error}=await SB.from('destinations').upsert(payload);if(error){console.error(error);return toast('Erreur pendant l’enregistrement.')}await sbRefresh();toast('Destination enregistrée');sbListDestinations()}
function sbEditVoyage(id){const x=id?SBCACHE.voyages.find(z=>z.id===id):{id:'',destination_id:'',title:'',subtitle:'',date:'',image:'assets/logo.jpg',price:'Sur demande',price_value:null,duration:'',departure:'Marseille',text:'',included:[],highlights:[],gallery:[],badge:'',active:true};section='voyages';const opts=SBCACHE.destinations.map(d=>`<option value="${esc(d.id)}" ${x.destination_id===d.id?'selected':''}>${esc(d.name)}</option>`).join('');$('#adminContent').innerHTML=sbEditorHeader('Voyage',id)+`<form class="admin-card admin-form" id="sbEdit"><div class="admin-fields-2"><div class="admin-field"><label>Titre *</label><input name="title" required value="${esc(x.title)}"></div><div class="admin-field"><label>Destination</label><select name="destination_id"><option value="">Aucune</option>${opts}</select></div></div><div class="admin-field"><label>Sous-titre</label><input name="subtitle" value="${esc(x.subtitle||'')}"></div><div class="admin-fields-2"><div class="admin-field"><label>Date / période</label><input name="date" value="${esc(x.date||'')}"></div><div class="admin-field"><label>Badge</label><input name="badge" value="${esc(x.badge||'')}"></div></div><div class="admin-fields-2"><div class="admin-field"><label>Prix affiché</label><input name="price" value="${esc(x.price||'')}"></div><div class="admin-field"><label>Prix numérique</label><input name="price_value" type="number" value="${esc(x.price_value??'')}"></div></div><div class="admin-fields-2"><div class="admin-field"><label>Durée</label><input name="duration" value="${esc(x.duration||'')}"></div><div class="admin-field"><label>Départ</label><input name="departure" value="${esc(x.departure||'Marseille')}"></div></div><div class="admin-field"><label>Description *</label><textarea name="text" required>${esc(x.text||'')}</textarea></div>${imageUploadField('image','Image principale',x.image,'voyages')}<div class="admin-fields-2"><div class="admin-field"><label>Inclus — un par ligne</label><textarea name="included">${esc(arrText(x.included))}</textarea></div><div class="admin-field"><label>Temps forts — un par ligne</label><textarea name="highlights">${esc(arrText(x.highlights))}</textarea></div></div>${galleryUploadField(x.gallery)}${sbFeaturedSwitch('voyage',x.id)}${sbSwitch(x.active,'Voyage visible')}<input type="hidden" name="id" value="${esc(x.id)}"><button class="admin-btn admin-btn-primary">Enregistrer</button></form>`;$('#sbEdit').addEventListener('submit',sbSaveVoyage);sbRenderGallery()}
async function sbSaveVoyage(e){e.preventDefault();const f=new FormData(e.currentTarget),id=f.get('id')||slug(f.get('title'))+'-'+Date.now().toString().slice(-4),featured=f.get('featured')==='on',payload={id,destination_id:f.get('destination_id')||null,title:String(f.get('title')).trim(),subtitle:String(f.get('subtitle')||'').trim(),date:String(f.get('date')||'').trim(),image:String(f.get('image')||'').trim(),price:String(f.get('price')||'Sur demande').trim(),price_value:f.get('price_value')?Number(f.get('price_value')):null,duration:String(f.get('duration')||'').trim(),departure:String(f.get('departure')||'Marseille').trim(),text:String(f.get('text')||'').trim(),included:lines(f.get('included')),highlights:lines(f.get('highlights')),gallery:lines(f.get('gallery')),badge:String(f.get('badge')||'').trim(),active:featured?true:f.get('active')==='on'};const {error}=await SB.from('voyages').upsert(payload);if(error){console.error(error);return toast('Erreur pendant l’enregistrement.')}try{await sbSaveFeatured('voyage',id,featured)}catch(err){console.error(err);return toast('Voyage enregistré, mais la mise à la une a échoué.')}if(payload.destination_id){const d=SBCACHE.destinations.find(x=>x.id===payload.destination_id);if(d&&!d.offer_id)await SB.from('destinations').update({offer_id:id}).eq('id',d.id)}await sbRefresh();toast(featured?'Voyage enregistré et mis à la une':'Voyage enregistré');sbListVoyages()}
function sbEditPublication(id){const x=id?SBCACHE.publications.find(z=>z.id===id):{id:'',title:'',date:new Intl.DateTimeFormat('fr-FR',{day:'numeric',month:'short'}).format(new Date()),text:'',image:'assets/logo.jpg',voyage_id:'',destination_id:'',active:true};section='publications';const vo=SBCACHE.voyages.map(v=>`<option value="${esc(v.id)}" ${x.voyage_id===v.id?'selected':''}>${esc(v.title)}</option>`).join(''),de=SBCACHE.destinations.map(d=>`<option value="${esc(d.id)}" ${x.destination_id===d.id?'selected':''}>${esc(d.name)}</option>`).join('');$('#adminContent').innerHTML=sbEditorHeader('Publication',id)+`<form class="admin-card admin-form" id="sbEdit"><div class="admin-fields-2"><div class="admin-field"><label>Titre *</label><input name="title" required value="${esc(x.title)}"></div><div class="admin-field"><label>Date affichée</label><input name="date" value="${esc(x.date||'')}"></div></div><div class="admin-field"><label>Texte *</label><textarea name="text" required>${esc(x.text||'')}</textarea></div>${imageUploadField('image','Image de la publication',x.image,'publications')}<div class="admin-fields-2"><div class="admin-field"><label>Voyage associé</label><select name="voyage_id"><option value="">Aucun</option>${vo}</select></div><div class="admin-field"><label>Destination associée</label><select name="destination_id"><option value="">Aucune</option>${de}</select></div></div>${sbFeaturedSwitch('publication',x.id)}${sbSwitch(x.active,'Publication visible')}<input type="hidden" name="id" value="${esc(x.id)}"><button class="admin-btn admin-btn-primary">Enregistrer</button></form>`;$('#sbEdit').addEventListener('submit',sbSavePublication)}
async function sbSavePublication(e){e.preventDefault();const f=new FormData(e.currentTarget),id=f.get('id')||slug(f.get('title'))+'-'+Date.now().toString().slice(-4),featured=f.get('featured')==='on',vid=f.get('voyage_id')||null,v=SBCACHE.voyages.find(x=>x.id===vid),payload={id,title:String(f.get('title')).trim(),date:String(f.get('date')||'').trim(),text:String(f.get('text')||'').trim(),image:String(f.get('image')||'').trim(),voyage_id:vid,destination_id:(v?.destination_id||f.get('destination_id')||null),active:featured?true:f.get('active')==='on'};const {error}=await SB.from('publications').upsert(payload);if(error){console.error(error);return toast('Erreur pendant l’enregistrement.')}try{await sbSaveFeatured('publication',id,featured)}catch(err){console.error(err);return toast('Publication enregistrée, mais la mise à la une a échoué.')}await sbRefresh();toast(featured?'Publication enregistrée et mise à la une':'Publication enregistrée');sbListPublications()}
async function sbToggle(table,id,active){const type=table==='voyages'?'voyage':table==='publications'?'publication':null;if(!active&&type&&sbIsFeatured(type,id)){const {error:se}=await SB.from('site_settings').upsert({key:'homepage',featured_type:null,featured_id:null,updated_at:new Date().toISOString()});if(se)return toast('Modification refusée.')}const {error}=await SB.from(table).update({active}).eq('id',id);if(error)return toast('Modification refusée.');await sbRefresh();toast(active?'Contenu publié':'Contenu masqué');sbRenderSection()}
async function sbDelete(table,id){if(table==='destinations'&&SBCACHE.voyages.some(v=>v.destination_id===id))return toast('Supprimez ou déplacez d’abord les voyages liés.');if(!confirm('Confirmer la suppression définitive ?'))return;const type=table==='voyages'?'voyage':table==='publications'?'publication':null;if(type&&sbIsFeatured(type,id))await SB.from('site_settings').upsert({key:'homepage',featured_type:null,featured_id:null,updated_at:new Date().toISOString()});const {error}=await SB.from(table).delete().eq('id',id);if(error){console.error(error);return toast('Suppression impossible.')}await sbRefresh();toast('Suppression effectuée');sbRenderSection()}
function sbSecurity(){const email=SBUSER?.email||'';$('#adminContent').innerHTML=`<div class="admin-head"><div><div class="kicker">Compte administrateur</div><h2>Compte & sécurité</h2><p class="muted">Gérez les informations et la sécurité de votre compte administrateur.</p></div><span class="security-badge">Rôle admin vérifié</span></div><div class="security-grid"><form class="admin-card admin-form" id="sbPassword"><h3>Changer le mot de passe</h3><div class="admin-field"><label>Nouveau mot de passe</label><input name="next" type="password" minlength="10" required autocomplete="new-password"></div><div class="admin-field"><label>Confirmer le nouveau mot de passe</label><input name="confirm" type="password" minlength="10" required autocomplete="new-password"></div><button class="admin-btn admin-btn-primary">Mettre à jour</button></form><div class="admin-card"><h3>Compte connecté</h3><p class="muted">Adresse e-mail</p><p><strong>${esc(email)}</strong></p><p class="muted">Rôle</p><p><span class="security-badge">Administrateur</span></p><hr style="border:0;border-top:1px solid #edf1f5;margin:22px 0"><p class="muted" style="font-size:13px;line-height:1.6">Cet espace est réservé aux comptes administrateurs autorisés.</p></div></div>`;$('#sbPassword').addEventListener('submit',sbChangePassword)}
async function sbChangePassword(e){e.preventDefault();const f=new FormData(e.currentTarget),a=String(f.get('next')),b=String(f.get('confirm'));if(a!==b)return toast('Les deux mots de passe sont différents.');if(a.length<10)return toast('Choisissez au moins 10 caractères.');const {error}=await SB.auth.updateUser({password:a});if(error){console.error(error);return toast('Impossible de changer le mot de passe.')}e.currentTarget.reset();toast('Mot de passe mis à jour')}
