
const DATA_URL='data.json';
let DATA=null;
const $=(s,el=document)=>el.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
async function load(){DATA=await fetch(DATA_URL).then(r=>r.json()); render();}
function shell(title,active,content){
document.title=title+' — New Age Travel France';
return `<div class="topbar"><div class="container inner"><span>✈️ Voyages au départ de Marseille</span><span>📞 ${esc(DATA.agency.phone)} · 📍 ${esc(DATA.agency.city)}</span></div></div>
<nav class="nav"><div class="container inner"><a class="brand" href="index.html"><img src="assets/logo.jpg"><span>New Age Travel France<small>Agence de voyage</small></span></a>
<div class="links"><a class="${active==='home'?'active':''}" href="index.html">Accueil</a><a class="${active==='dest'?'active':''}" href="destinations.html">Destinations</a><a class="${active==='offers'?'active':''}" href="offres.html">Offres</a><a class="${active==='posts'?'active':''}" href="publications.html">Actualités</a><a class="${active==='agency'?'active':''}" href="agence.html">L’agence</a><a class="${active==='contact'?'active':''}" href="contact.html">Contact</a><a class="btn btn-primary" href="contact.html">Demander un devis</a></div><button class="menu" onclick="toggleMenu()">☰</button></div></nav>${content}
<footer class="footer"><div class="container footer-grid"><div><div class="brand"><img src="assets/logo.jpg"><span>New Age Travel France<small>Marseille</small></span></div><p>Agence de voyage à Marseille.</p></div><div><h4>Explorer</h4><a href="destinations.html">Destinations</a><a href="offres.html">Offres</a><a href="publications.html">Actualités</a></div><div><h4>Agence</h4><a href="agence.html">L’agence</a><a href="contact.html">Contact</a></div><div><h4>Contact</h4><a href="tel:+33465859350">${esc(DATA.agency.phone)}</a><p>${esc(DATA.agency.address)}</p></div></div><div class="container footer-bottom">© 2026 New Age Travel France · Données commerciales à confirmer avant réservation.</div></footer>`}
function cards(items){
return items.map(d=>`<article class="card"><div class="card-media"><span class="tag">${esc(d.region||d.date)}</span><img src="${esc(d.image)}" alt="${esc(d.name||d.title)}"></div><div class="card-body"><h3>${esc(d.name||d.title)}</h3><p class="meta">${esc(d.description||d.text||'')}</p>${d.price?`<div class="price">${esc(d.price)}</div>`:''}<a class="btn btn-dark" href="contact.html?destination=${encodeURIComponent(d.name||d.title)}">Demander les détails</a></div></article>`).join('');
}
function render(){
const path=location.pathname.split('/').pop()||'index.html';
if(path==='index.html'||path===''){
const featured=DATA.destinations.slice(0,3);
$('#app').innerHTML=shell('Accueil','home',`<header class="hero"><div class="container"><div><span class="eyebrow">New Age Travel France · Marseille</span><h1>Le monde commence par un billet.</h1><p>Des voyages soigneusement sélectionnés et un accompagnement humain pour préparer votre prochaine escapade.</p><div class="hero-actions"><a class="btn btn-primary" href="offres.html">Voir les offres →</a><a class="btn btn-light" href="contact.html">Parler à l’agence</a></div></div><div class="hero-card"><img src="assets/cairo.jpg" alt="Le Caire"></div></div></header><div class="container searchbox"><div class="field"><label>Destination</label><input id="q" placeholder="Ex. Le Caire, Tunisie…"></div><div class="field"><label>Type</label><select id="type"><option value="">Tout type de voyage</option><option value="afrique">Afrique</option><option value="spirituel">Spirituel</option><option value="mediterranee">Méditerranée</option></select></div><div class="field"><label>Départ</label><select><option>Marseille</option></select></div><button class="btn btn-dark" onclick="search()">Rechercher</button></div><section class="section"><div class="container"><div class="section-head"><div><div class="kicker">À la une</div><h2>Des destinations qui donnent envie de partir.</h2><p class="lead">Inspirations issues de l’univers de l’agence.</p></div><a class="btn btn-light" href="destinations.html">Tout voir</a></div><div class="grid grid-3" id="featured">${cards(featured)}</div><p class="meta" style="margin-top:15px">* Prix et conditions à confirmer auprès de l’agence.</p></div></section><section class="section" style="padding-top:0"><div class="container"><div class="banner"><div><h3>Une envie précise ?</h3><p>Destination, période et budget : racontez-nous votre projet.</p></div><a class="btn btn-light" href="contact.html">Demander un devis</a></div></div></section>`);
}
else if(path==='destinations.html'){
$('#app').innerHTML=shell('Destinations','dest',`<header class="page-hero"><div class="container"><div class="kicker">Explorer</div><h1>Où souhaitez-vous partir ?</h1><p class="lead">Recherche et filtres dynamiques alimentés par data.json.</p></div></header><section class="section"><div class="container"><div class="filters"><button class="filter active" onclick="filterDest('all',this)">Toutes</button><button class="filter" onclick="filterDest('afrique',this)">Afrique</button><button class="filter" onclick="filterDest('spirituel',this)">Spirituel</button><button class="filter" onclick="filterDest('mediterranee',this)">Méditerranée</button></div><div class="grid grid-3" id="destGrid">${cards(DATA.destinations)}</div><p class="meta">Les prix et disponibilités sont indicatifs et doivent être confirmés.</p></div></section>`);
}
else if(path==='offres.html'){
$('#app').innerHTML=shell('Offres','offers',`<header class="page-hero"><div class="container"><div class="kicker">Séjours</div><h1>Les offres à la une.</h1><p class="lead">Modifiez data.json pour ajouter ou retirer une offre sans toucher au HTML.</p></div></header><section class="section"><div class="container grid grid-3">${cards(DATA.offers)}</div></section>`);
}
else if(path==='publications.html'){
$('#app').innerHTML=shell('Actualités','posts',`<header class="page-hero"><div class="container"><div class="kicker">Publications</div><h1>Les dernières inspirations.</h1><p class="lead">Une section éditoriale gérée par les données.</p></div></header><section class="section"><div class="container grid grid-3">${cards(DATA.posts)}</div></section>`);
}
else if(path==='agence.html'){
$('#app').innerHTML=shell('L’agence','agency',`<header class="page-hero"><div class="container"><div class="kicker">New Age Travel France</div><h1>Une agence ancrée à Marseille.</h1><p class="lead">Identité et informations publiques reprises à partir des éléments fournis.</p></div></header><section class="section"><div class="container contact"><div class="info-box"><img src="assets/logo.jpg" style="width:130px;border-radius:50%;margin-bottom:20px"><h2>Notre univers</h2><p>New Age Travel France est présentée comme une agence de voyage située à Marseille.</p><p><strong>Adresse</strong><br>${esc(DATA.agency.address)}</p><p><strong>Téléphone</strong><br><a href="tel:+33465859350">${esc(DATA.agency.phone)}</a></p></div><div class="info-box"><h2>Nos visuels</h2><img src="assets/companies.jpg" alt="Compagnies partenaires" style="border-radius:18px"><p class="meta">Les logos visibles sur le visuel sont présentés ici comme éléments graphiques, sans déduire de relation contractuelle.</p></div></div></section>`);
}
else {
$('#app').innerHTML=shell('Contact','contact',`<header class="page-hero"><div class="container"><div class="kicker">Contact</div><h1>Construisons votre voyage.</h1><p class="lead">Formulaire côté navigateur, prêt à être relié à un service de formulaire.</p></div></header><section class="section"><div class="container contact"><div class="info-box"><h2>New Age Travel France</h2><p>📍 ${esc(DATA.agency.address)}</p><p>📞 <a href="tel:+33465859350">${esc(DATA.agency.phone)}</a></p><a class="btn btn-primary" href="tel:+33465859350">Appeler maintenant</a></div><div class="info-box"><form id="form"><div class="form-row"><div class="input"><label>Nom</label><input name="name" required></div><div class="input"><label>Téléphone</label><input name="phone"></div></div><div class="input"><label>Email</label><input name="email" type="email" required></div><div class="form-row"><div class="input"><label>Destination</label><input id="destination" name="destination"></div><div class="input"><label>Période</label><input name="period"></div></div><div class="input"><label>Projet</label><textarea name="message" required></textarea></div><button class="btn btn-primary">Préparer ma demande →</button></form></div></div></section>`);
const d=new URLSearchParams(location.search).get('destination'); if(d)$('#destination').value=d;
$('#form').addEventListener('submit',e=>{e.preventDefault(); const f=new FormData(e.target); const body=encodeURIComponent([...f.entries()].map(x=>x[0]+': '+x[1]).join('\\n')); location.href='mailto:?subject='+encodeURIComponent('Demande de voyage')+'&body='+body;});
}
}
function filterDest(cat,btn){document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));btn.classList.add('active');const items=cat==='all'?DATA.destinations:DATA.destinations.filter(x=>x.category===cat);$('#destGrid').innerHTML=cards(items);}
function search(){const q=($('#q').value||'').toLowerCase(),type=$('#type').value;const items=DATA.destinations.filter(x=>(!q||x.name.toLowerCase().includes(q)||x.description.toLowerCase().includes(q))&&(!type||x.category===type));location.href='destinations.html';setTimeout(()=>$('#destGrid').innerHTML=cards(items),0);}
function toggleMenu(){const l=document.querySelector('.links');if(!l)return;l.style.display=l.style.display==='flex'?'':'flex';l.style.flexDirection='column';l.style.position='absolute';l.style.top='68px';l.style.right='18px';l.style.padding='18px';l.style.background='#fff';l.style.border='1px solid #e7ebf2';l.style.borderRadius='18px';l.style.boxShadow='0 20px 50px rgba(8,43,99,.15)';}
load().catch(err=>document.getElementById('app').innerHTML='<div class="container section"><h1>Impossible de charger les données.</h1><p>Ouvrez le site via GitHub Pages ou un serveur local.</p></div>');
